/**
 * Resolves customizable icon references (lucide name or image URL) to renderable
 * values for the {@link Icon} component.
 *
 * The lucide registry is generated by the CLI (`pnpm gen`) at
 * `src/generated/icons.ts` and imports ONLY the icons referenced by
 * `config/site.config.ts` — so the bundle stays small while still supporting any
 * lucide icon name (just set it in config and re-run gen).
 */
import type { Component } from 'vue'
import type { IconRef, IconSpec } from '@/shared/types'
import { iconRegistry } from '@/generated/icons'

const FALLBACK_NAME = 'CircleHelp'

export function isImageIcon(ref: IconRef | undefined): ref is IconSpec & { img: string } {
  return !!ref && typeof ref === 'object' && !!ref.img
}

/** Resolve a lucide component by name (falls back to CircleHelp, then null). */
export function resolveIcon(ref: IconRef | undefined): Component | null {
  if (!ref) return null
  const name = typeof ref === 'string' ? ref : ref.lucide
  if (!name) return null
  const registry = iconRegistry as Record<string, Component>
  return registry[name] ?? registry[FALLBACK_NAME] ?? null
}
