#!/usr/bin/env node
/**
 * unnc-vg — config CLI for the UNNC admission verifier gateway.
 *
 *   gen        Generate src/generated/icons.ts — a tiny registry importing only
 *              the lucide icons referenced by config/site.config.ts (keeps the
 *              bundle small). Run after changing any icon in config.
 *   validate   Check config/site.config.ts: gateway settings + required i18n
 *              message keys for every locale.
 *   help       Show usage.
 *
 * Run in dev via tsx (`pnpm gen` / `pnpm validate`). tsup bundles a distributable
 * copy (`pnpm build:cli` -> dist-cli/index.js); because config is loaded
 * dynamically from process.cwd(), the bundled CLI also reads the caller's config
 * under Node 24 (native TS type-stripping).
 */
import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

import type { IconRef, Locale, SiteConfig } from '../shared/types'

const cwd = process.cwd()
const ICONS_FILE = resolve(cwd, 'src/generated/icons.ts')
const CONFIG_FILE = resolve(cwd, 'config/site.config.ts')
const FALLBACK_ICON = 'CircleHelp'

/* ----------------------------------------------------------------- config -- */

async function loadConfig(): Promise<SiteConfig> {
  if (!existsSync(CONFIG_FILE)) {
    throw new Error(`config/site.config.ts not found at ${CONFIG_FILE}`)
  }
  const mod = (await import(pathToFileURL(CONFIG_FILE).href)) as { default: SiteConfig }
  return mod.default
}

/* ----------------------------------------------------------- icon-codegen -- */

function collectIconNames(config: SiteConfig): string[] {
  const names = new Set<string>([FALLBACK_ICON])
  for (const ref of Object.values(config.icons) as IconRef[]) {
    const name = typeof ref === 'string' ? ref : ref?.lucide
    if (name) names.add(name)
  }
  return [...names]
}

/**
 * Validate the config's icon names against lucide-vue-next and write a tiny
 * registry module importing only the icons actually used — keeping the SPA
 * bundle small while allowing any lucide name in config.
 */
async function generateIcons(config: SiteConfig): Promise<void> {
  const wanted = collectIconNames(config)

  let valid = wanted
  let lucide: Record<string, unknown> | null = null
  try {
    lucide = (await import('lucide-vue-next')) as Record<string, unknown>
  } catch {
    // lucide-vue-next not resolvable from the CLI — emit names unvalidated.
  }

  if (lucide) {
    valid = wanted.filter((n) => typeof lucide![n] !== 'undefined')
    const invalid = wanted.filter(
      (n) => n !== FALLBACK_ICON && typeof lucide![n] === 'undefined',
    )
    if (invalid.length > 0) {
      console.warn(
        `  ⚠ Unknown lucide icon(s) in config: ${invalid.join(', ')}. ` +
          `They will render as the fallback (${FALLBACK_ICON}).`,
      )
    }
  }
  if (!valid.includes(FALLBACK_ICON)) valid.push(FALLBACK_ICON)

  const deduped = [...new Set(valid)].sort()
  const imports = deduped.join(', ')
  const entries = deduped.map((n) => `  ${n},`).join('\n')
  const body =
    `// AUTO-GENERATED by \`pnpm gen\` — do not edit by hand.\n` +
    `// Only the icons referenced in config/site.config.ts are imported, so the\n` +
    `// lucide-vue-next bundle stays small. Change an icon in config then re-run gen.\n` +
    `import type { Component } from 'vue'\n` +
    `import { ${imports} } from 'lucide-vue-next'\n\n` +
    `export const iconRegistry: Record<string, Component> = {\n${entries}\n}\n`

  await mkdir(resolve(ICONS_FILE, '..'), { recursive: true })
  await writeFile(ICONS_FILE, body, 'utf8')
  console.log(
    `✓ Wrote icon registry (${deduped.length} icons) → ${ICONS_FILE.replace(cwd + '/', '')}`,
  )
}

/* ------------------------------------------------------------------ gen --- */

async function gen(): Promise<void> {
  const config = await loadConfig()
  await generateIcons(config)
}

/* ------------------------------------------------------------- validate --- */

function deepGet(obj: unknown, path: string): unknown {
  return path.split('.').reduce<unknown>((acc, key) => {
    if (acc && typeof acc === 'object') {
      return (acc as Record<string, unknown>)[key]
    }
    return undefined
  }, obj)
}

const REQUIRED_KEYS = [
  'brand.title',
  'brand.subtitle',
  'verify.heading',
  'verify.subheading',
  'verify.nameLabel',
  'verify.namePlaceholder',
  'verify.idLabel',
  'verify.idPlaceholder',
  'verify.submit',
  'verify.submitting',
  'verify.hint',
  'errors.emptyName',
  'errors.badIdFormat',
  'errors.notAdmitted',
  'errors.captcha',
  'errors.network',
  'errors.generic',
  'admission.title',
  'admission.name',
  'admission.university',
  'admission.date',
  'admission.detail',
  'welcome.badge',
  'welcome.title',
  'welcome.body',
  'welcome.imageAlt',
  'welcome.back',
  'theme.toggle',
  'lang.label',
  'footer',
]

async function validate(): Promise<void> {
  const config = await loadConfig()
  const errors: string[] = []

  if (!config.locales || config.locales.length === 0) errors.push('locales is empty')
  if (!config.defaultLocale) errors.push('defaultLocale is missing')
  else if (!config.locales.includes(config.defaultLocale)) {
    errors.push(`defaultLocale "${config.defaultLocale}" is not listed in locales`)
  }

  const g = config.gateway
  if (!g) {
    errors.push('gateway is missing')
  } else {
    if (!['live', 'mock'].includes(g.mode)) errors.push(`gateway.mode "${g.mode}" must be 'live' or 'mock'`)
    if (!g.baseUrl || !/^https?:\/\//.test(g.baseUrl)) {
      errors.push('gateway.baseUrl must be an http(s) URL')
    }
    if (
      !g.proxy ||
      (!g.proxy.startsWith('/') &&
        !g.proxy.includes('{url}') &&
        !g.proxy.includes('{urlEncoded}') &&
        !/^https?:\/\//.test(g.proxy))
    ) {
      errors.push(
        "gateway.proxy must be a local prefix ('/__portal'), a {url}/{urlEncoded} template, or a URL prefix",
      )
    }
    if (!Number.isFinite(g.maxCaptchaRounds) || g.maxCaptchaRounds < 1) {
      errors.push('gateway.maxCaptchaRounds must be >= 1')
    }
    if (!Number.isFinite(g.maxOffsetTries) || g.maxOffsetTries < 1) {
      errors.push('gateway.maxOffsetTries must be >= 1')
    }
  }

  if (!config.messages) errors.push('messages is missing')

  for (const loc of config.locales) {
    const messages = config.messages[loc as Locale]
    if (!messages) {
      errors.push(`messages.${loc} is missing`)
      continue
    }
    for (const key of REQUIRED_KEYS) {
      const value = deepGet(messages, key)
      if (value === undefined || value === null || value === '') {
        errors.push(`messages.${loc}.${key} is missing`)
      }
    }
  }

  if (errors.length > 0) {
    console.error(`✗ ${errors.length} config problem(s):`)
    for (const e of errors) console.error(`  - ${e}`)
    process.exit(1)
  }
  console.log('✓ site.config.ts looks good.')
}

/* ----------------------------------------------------------------- help --- */

function help(): void {
  console.log(
    [
      'unnc-vg — UNNC admission verifier gateway CLI',
      '',
      'Usage:',
      '  unnc-vg gen        Generate src/generated/icons.ts from config icons',
      '  unnc-vg validate   Validate config/site.config.ts (gateway + i18n keys)',
      '  unnc-vg help       Show this message',
    ].join('\n'),
  )
}

/* ----------------------------------------------------------------- main --- */

async function main(): Promise<void> {
  const cmd = process.argv[2]
  switch (cmd) {
    case 'gen':
      await gen()
      break
    case 'validate':
      await validate()
      break
    case undefined:
    case 'help':
    case '--help':
    case '-h':
      help()
      break
    default:
      console.error(`Unknown command: ${cmd}\n`)
      help()
      process.exit(1)
  }
}

await main()
