import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Baseline schema — every table at its post-rename (page_*) spelling.
 *
 * Generated by building the schema from the entities on a scratch database and
 * freezing the resulting DDL (see docs/DATABASE-NAMING.md). Only runs on FRESH
 * databases: existing v1 databases (org_* tables) get this migration marked as
 * applied by the journal bootstrap in `server/utils/database.ts`, and move
 * straight on to OrgToPageRename.
 *
 * Guarded with IF NOT EXISTS so a partially-created database is repaired
 * instead of crashing.
 */
export class Init1760000000000 implements MigrationInterface {
  name = 'Init1760000000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of INIT_DDL) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const table of INIT_TABLES) {
      await queryRunner.query(`DROP TABLE IF EXISTS ${table}`)
    }
  }
}

export const INIT_TABLES = [
  'users',
  'sessions',
  'pages',
  'page_settings',
  'page_images',
  'page_members',
  'page_events',
  'page_daily_stats',
  'page_reminder_sents',
  'page_redirects',
  'page_verified_identities',
  'user_page_notification_prefs',
  'audit_events',
  'passkeys',
  'mail_configs',
  'app_settings',
]

export const INIT_DDL: string[] = [
  // table: users
  'CREATE TABLE IF NOT EXISTS "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "email" text NOT NULL, "password_hash" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "trusted_until" datetime, "role" text NOT NULL DEFAULT (\'admin\'), "page_limit" integer, "locale" text, "notify_expiry" boolean NOT NULL DEFAULT (1), "tz" text, "reminder_slots" text, "reminder_time" text);',
  // table: sessions
  'CREATE TABLE IF NOT EXISTS "sessions" ("id" text PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: pages
  'CREATE TABLE IF NOT EXISTS "pages" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "owner_id" integer NOT NULL, "slug" text NOT NULL, "name" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: page_settings
  'CREATE TABLE IF NOT EXISTS "page_settings" ("page_id" integer PRIMARY KEY NOT NULL, "config" text NOT NULL, "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: page_images
  'CREATE TABLE IF NOT EXISTS "page_images" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "key" text NOT NULL, "mime" text NOT NULL, "base64" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: page_members
  'CREATE TABLE IF NOT EXISTS "page_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "user_id" integer, "invited_email" text NOT NULL, "invite_token" text, "role" text NOT NULL, "status" text NOT NULL DEFAULT (\'pending\'), "invited_by" integer NOT NULL, "expires_at" datetime, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "accepted_at" datetime);',
  // table: page_events
  'CREATE TABLE IF NOT EXISTS "page_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "type" text NOT NULL, "outcome" text, "mode" text, "name" text, "id_hash" text, "ip_hash" text, "locale" text, "country" text, "device" text, "browser" text, "os" text, "referer" text, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: page_daily_stats
  'CREATE TABLE IF NOT EXISTS "page_daily_stats" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "day" text NOT NULL, "metric" text NOT NULL, "count" integer NOT NULL DEFAULT (0));',
  // table: page_reminder_sents
  'CREATE TABLE IF NOT EXISTS "page_reminder_sents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "user_id" integer, "expires_at" text NOT NULL, "kind" text NOT NULL, "sent_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: page_redirects
  'CREATE TABLE IF NOT EXISTS "page_redirects" ("old_slug" text PRIMARY KEY NOT NULL, "page_id" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: page_verified_identities
  'CREATE TABLE IF NOT EXISTS "page_verified_identities" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "name" text NOT NULL, "id_hash" text NOT NULL, "verified_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: user_page_notification_prefs
  'CREATE TABLE IF NOT EXISTS "user_page_notification_prefs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer NOT NULL, "user_id" integer NOT NULL, "notify_expiry" boolean, "reminder_slots" text, "reminder_time" text);',
  // table: passkeys
  'CREATE TABLE IF NOT EXISTS "passkeys" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "credential_id" text NOT NULL, "user_id" integer NOT NULL, "public_key" blob NOT NULL, "counter" integer NOT NULL DEFAULT (0), "transports" text, "device_type" text, "backed_up" boolean NOT NULL DEFAULT (0), "nickname" text, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: mail_configs
  'CREATE TABLE IF NOT EXISTS "mail_configs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "smtp_server" text NOT NULL DEFAULT (\'\'), "smtp_port" integer NOT NULL DEFAULT (587), "use_ssl" boolean NOT NULL DEFAULT (0), "use_tls" boolean NOT NULL DEFAULT (1), "use_password" boolean NOT NULL DEFAULT (1), "sender_email" text NOT NULL DEFAULT (\'\'), "sender_email_display" text NOT NULL DEFAULT (\'\'), "sender_domain" text NOT NULL DEFAULT (\'\'), "sender_password" text NOT NULL DEFAULT (\'\'), "max_len_recipient_email" integer NOT NULL DEFAULT (64), "max_len_subject" integer NOT NULL DEFAULT (255), "max_len_body" integer NOT NULL DEFAULT (50000), "provider" text NOT NULL DEFAULT (\'smtp\'), "post_url" text NOT NULL DEFAULT (\'\'), "post_schema" text NOT NULL DEFAULT (\'smtogo\'), "post_auth_token" text NOT NULL DEFAULT (\'\'), "post_field_map" text NOT NULL DEFAULT (\'\'), "post_schemas" text NOT NULL DEFAULT (\'\'), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // table: app_settings
  'CREATE TABLE IF NOT EXISTS "app_settings" ("key" text PRIMARY KEY NOT NULL, "value" text NOT NULL DEFAULT (\'{}\'));',
  // table: audit_events
  'CREATE TABLE IF NOT EXISTS "audit_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "page_id" integer, "action" text NOT NULL, "outcome" text, "actor_type" text, "user_id" integer, "email" text, "name" text, "ip_hash" text, "detail" text, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP));',
  // index: uq_users_email
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_email" ON "users" ("email");',
  // index: uq_organizations_slug
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_organizations_slug" ON "pages" ("slug");',
  // index: uq_org_images_org_key
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_org_images_org_key" ON "page_images" ("page_id", "key");',
  // index: idx_org_members_user
  'CREATE INDEX IF NOT EXISTS "idx_org_members_user" ON "page_members" ("user_id");',
  // index: idx_org_members_org
  'CREATE INDEX IF NOT EXISTS "idx_org_members_org" ON "page_members" ("page_id");',
  // index: uq_org_members_token
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_org_members_token" ON "page_members" ("invite_token");',
  // index: uq_org_members_org_email
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_org_members_org_email" ON "page_members" ("page_id", "invited_email");',
  // index: idx_org_events_type
  'CREATE INDEX IF NOT EXISTS "idx_org_events_type" ON "page_events" ("page_id", "type", "created_at");',
  // index: idx_org_events_org_time
  'CREATE INDEX IF NOT EXISTS "idx_org_events_org_time" ON "page_events" ("page_id", "created_at");',
  // index: idx_org_daily_stats_org_day
  'CREATE INDEX IF NOT EXISTS "idx_org_daily_stats_org_day" ON "page_daily_stats" ("page_id", "day");',
  // index: uq_org_daily_stats_day_metric
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_org_daily_stats_day_metric" ON "page_daily_stats" ("page_id", "day", "metric");',
  // index: uq_org_reminder_org_user_date_kind
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_org_reminder_org_user_date_kind" ON "page_reminder_sents" ("page_id", "user_id", "expires_at", "kind");',
  // index: idx_org_verified_identity_org_hash
  'CREATE UNIQUE INDEX IF NOT EXISTS "idx_org_verified_identity_org_hash" ON "page_verified_identities" ("page_id", "id_hash");',
  // index: idx_user_org_pref_user
  'CREATE INDEX IF NOT EXISTS "idx_user_org_pref_user" ON "user_page_notification_prefs" ("user_id");',
  // index: uq_user_org_pref_org_user
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_org_pref_org_user" ON "user_page_notification_prefs" ("page_id", "user_id");',
  // index: idx_passkeys_user
  'CREATE INDEX IF NOT EXISTS "idx_passkeys_user" ON "passkeys" ("user_id");',
  // index: uq_passkeys_credential_id
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_passkeys_credential_id" ON "passkeys" ("credential_id");',
  // index: uq_mail_configs_user
  'CREATE UNIQUE INDEX IF NOT EXISTS "uq_mail_configs_user" ON "mail_configs" ("user_id");',
  // index: idx_audit_user
  'CREATE INDEX IF NOT EXISTS "idx_audit_user" ON "audit_events" ("user_id", "created_at");',
  // index: idx_audit_action
  'CREATE INDEX IF NOT EXISTS "idx_audit_action" ON "audit_events" ("action", "created_at");',
  // index: idx_audit_org
  'CREATE INDEX IF NOT EXISTS "idx_audit_org" ON "audit_events" ("page_id", "created_at");',
  // index: idx_audit_created
  'CREATE INDEX IF NOT EXISTS "idx_audit_created" ON "audit_events" ("created_at");',
]
