import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=AddTrustGrants` — diff of the entities
 * against ./data/app.db. Review before committing: generated diffs describe structural
 * changes, not data backfills (add those by hand if needed).
 */
export class AddTrustGrants1787780528884 implements MigrationInterface {
  name = 'AddTrustGrants1787780528884'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  'CREATE TABLE "trust_grants" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "device_hash" text NOT NULL, "user_id" integer, "name" text NOT NULL, "user_agent" text, "trusted_until" datetime NOT NULL, "last_refreshed_at" datetime NOT NULL, "revoked_at" datetime, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))',
  'CREATE INDEX "idx_trust_grants_user" ON "trust_grants" ("user_id")',
  'CREATE UNIQUE INDEX "uq_trust_grants_device" ON "trust_grants" ("device_hash")',
]

const DOWN: string[] = [
  'DROP TABLE "trust_grants"',
  'DROP INDEX "idx_trust_grants_user"',
  'DROP INDEX "uq_trust_grants_device"',
]
