// AUTO-GENERATED by server/scripts/syncMigrations.ts — do not edit by hand.
// Imports every migration in this directory so the DataSource runs them all
// without a hand-maintained list. Regenerated by `pnpm db:generate` and on install.
import { Init1784089805639 } from './1784089805639-Init'
import { AddJwtTrust1784107140834 } from './1784107140834-AddJwtTrust'
import { AddUserRole1784284851394 } from './1784284851394-AddUserRole'
import { AddPasskeys1784390766498 } from './1784390766498-AddPasskeys'
import { OrgSharingStats1784395098597 } from './1784395098597-OrgSharingStats'
import { AddAppSettingsAndMailConfigs1784398224164 } from './1784398224164-AddAppSettingsAndMailConfigs'

export const migrationClasses = [
  Init1784089805639,
  AddJwtTrust1784107140834,
  AddUserRole1784284851394,
  AddPasskeys1784390766498,
  OrgSharingStats1784395098597,
  AddAppSettingsAndMailConfigs1784398224164,
]
