/**
 * Regenerate `server/migrations/index.ts` so it imports every migration in the
 * directory — no hand-maintained list anywhere. The DataSource imports this
 * barrel, so all migrations run automatically.
 *
 * Run by `pnpm db:generate` (after creating a migration) and by `pnpm install`
 * (postinstall) so a fresh checkout / pull stays in sync.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const migrationsDir = resolve(__dirname, '..', 'migrations')
const barrelPath = resolve(migrationsDir, 'index.ts')

const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
  .sort()

const entries = files.map((file) => {
  const src = readFileSync(resolve(migrationsDir, file), 'utf-8')
  const cls = (src.match(/export class (\w+)/) || [])[1]
  if (!cls) throw new Error(`Migration ${file} has no \`export class\`.`)
  return { file, cls }
})

const barrel = `// AUTO-GENERATED by server/scripts/syncMigrations.ts — do not edit by hand.
// Imports every migration in this directory so the DataSource runs them all
// without a hand-maintained list. Regenerated by \`pnpm db:generate\` and on install.
${entries.map((e) => `import { ${e.cls} } from './${e.file.replace(/\.ts$/, '')}'`).join('\n')}

export const migrationClasses = [
${entries.map((e) => `  ${e.cls},`).join('\n')}
]
`

// Only write when content changed — avoids pointless churn / git diffs.
const existing = existsSync(barrelPath) ? readFileSync(barrelPath, 'utf-8') : ''
if (existing === barrel) {
  console.log(`[sync-migrations] ${entries.length} migration(s), barrel up to date.`)
} else {
  writeFileSync(barrelPath, barrel)
  console.log(
    `[sync-migrations] indexed ${entries.length} migration(s) → server/migrations/index.ts`,
  )
}
