import 'reflect-metadata'
import 'better-sqlite3'
import { DataSource } from 'typeorm'
import type { Logger } from 'typeorm'
import { User } from '#server/entities/user.entity'
import { Session } from '#server/entities/session.entity'
import { Organization } from '#server/entities/organization.entity'
import { OrgSetting } from '#server/entities/orgSetting.entity'
import { OrgImage } from '#server/entities/orgImage.entity'
import { Passkey } from '#server/entities/passkey.entity'
import { Verification } from '#server/entities/verification.entity'
import { AppSetting } from '#server/entities/appSetting.entity'
import { OrgMember } from '#server/entities/orgMember.entity'
import { OrgEvent } from '#server/entities/orgEvent.entity'
import { OrgDailyStat } from '#server/entities/orgDailyStat.entity'
import { MailConfig } from '#server/entities/mailConfig.entity'

// Migrations own the schema. The barrel (`server/migrations/index.ts`) imports
// every migration file in that directory — auto-regenerated by db:generate and
// pnpm install — so the DataSource runs them all with no hand-maintained list.
import { migrationClasses } from '../migrations/index'

const dbPath = process.env.DB_PATH || './data/app.db'

/**
 * Quiet TypeORM logger for startup: surfaces schema-build + migration activity
 * with a `[db]` prefix, while suppressing the noisy per-query log.
 */
class StartupLogger implements Logger {
  logQuery(): void {
    // suppressed — routine SELECT/INSERT etc. would flood startup logs
  }
  logQueryError(error: string | Error, query: string): void {
    console.error(`[db] query error: ${error}\n  ${query}`)
  }
  logQuerySlow(): void {}
  logSchemaBuild(message: string): void {
    console.log(`[db] schema · ${message}`)
  }
  logMigration(message: string): void {
    console.log(`[db] migration · ${message}`)
  }
  log(level: 'log' | 'info' | 'warn', message: unknown): void {
    if (level === 'warn') console.warn(`[db] ${message}`)
    else console.log(`[db] ${message}`)
  }
}

export const AppDataSource = new DataSource({
  type: 'better-sqlite3',
  database: dbPath,
  entities: [
    User,
    Session,
    Organization,
    OrgSetting,
    OrgImage,
    Verification,
    AppSetting,
    Passkey,
    OrgMember,
    OrgEvent,
    OrgDailyStat,
    MailConfig,
  ],
  // Schema is owned by migrations — initDataSource() runs pending ones on boot
  // (no synchronize()). db:generate creates new ones by diffing the entities
  // against a migrations-built baseline DB, never the live dev DB.
  migrations: migrationClasses,
  synchronize: false,
  logging: ['schema', 'migration', 'error', 'warn'],
  logger: new StartupLogger(),
})

async function tableExists(name: string): Promise<boolean> {
  const rows = await AppDataSource.query(
    "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
    [name],
  )
  return Array.isArray(rows) && rows.length > 0
}

async function sqliteTables(): Promise<string[]> {
  const rows = (await AppDataSource.query(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' ORDER BY name",
  )) as { name: string }[]
  return rows.map((r) => r.name)
}

/**
 * A DB previously run under `synchronize()` (or partially migrated) has its
 * entity tables but a migration journal that doesn't reflect every configured
 * migration — either no `migrations` table at all, or one missing rows. Mark
 * each unrecorded migration as already-applied so the immediately-following
 * runMigrations() won't replay its CREATE statements (which would conflict with
 * the existing tables). The schema already matches the entities, so this is
 * safe — it only brings the journal in line. Idempotent (inserts only the
 * missing rows, so it's also safe on a partially-migrated DB).
 *
 * TypeORM identifies migrations by class name, with timestamp = the last 13
 * chars of that name (see MigrationExecutor.getMigrations), which we replicate.
 */
async function baselineLegacyDb(): Promise<void> {
  await AppDataSource.query(
    'CREATE TABLE IF NOT EXISTS "migrations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" integer NOT NULL, "name" text NOT NULL)',
  )
  let inserted = 0
  for (const m of AppDataSource.migrations as ReadonlyArray<{ name: string }>) {
    const className = m.name
    const present = (await AppDataSource.query('SELECT name FROM migrations WHERE name = ?', [
      className,
    ])) as unknown[]
    if (present.length) continue
    const timestamp = parseInt(className.slice(-13), 10) || 0
    await AppDataSource.query('INSERT INTO "migrations" ("timestamp", "name") VALUES (?, ?)', [
      timestamp,
      className,
    ])
    inserted++
  }
  if (inserted) {
    console.log(`[db] legacy/incomplete journal — marked ${inserted} migration(s) as applied`)
  }
}

/** Count of rows in the `migrations` table (0 if the table doesn't exist). */
async function countAppliedMigrations(): Promise<number> {
  if (!(await tableExists('migrations'))) return 0
  const rows = (await AppDataSource.query('SELECT COUNT(*) AS c FROM migrations')) as {
    c: number
  }[]
  return rows[0]?.c ?? 0
}

async function logMigrationStatus(): Promise<void> {
  if (!(await tableExists('migrations'))) {
    console.log('[db] migrations · none applied yet')
    return
  }
  const rows = (await AppDataSource.query(
    'SELECT timestamp, name FROM migrations ORDER BY timestamp',
  )) as { timestamp: number; name: string }[]
  console.log(`[db] migrations · ${rows.length} applied`)
  for (const r of rows) console.log(`[db]   · ${r.name}`)
}

export async function initDataSource(): Promise<void> {
  if (AppDataSource.isInitialized) return
  await AppDataSource.initialize()
  // If entity tables already exist (a synchronized or partially-migrated DB)
  // but the journal doesn't list every configured migration, reconcile it so
  // runMigrations() won't replay CREATEs that would collide with existing tables.
  if (
    (await tableExists('users')) &&
    (await countAppliedMigrations()) < AppDataSource.migrations.length
  ) {
    await baselineLegacyDb()
  }
  await AppDataSource.runMigrations()
  await logMigrationStatus()
  const tables = await sqliteTables()
  console.log(`[db] ready · ${dbPath} · ${tables.length} table(s)`)
}

export async function closeDataSource(): Promise<void> {
  if (AppDataSource.isInitialized) {
    await AppDataSource.destroy()
  }
}
